version: '3.9'

services:
  web:
    restart: unless-stopped
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - backend
    env_file:
      - ../.env
    volumes:
      - ./web/src:/app/public
    ports:
      - 80:80

  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ../.env
    expose:
      - 8000